language: php

php:
  - 8.0
  - 8.1

before_script:
  - 'composer install --prefer-source'

script: vendor/bin/codecept run --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
